name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      # Install Serverless Framework
      - name: Install Serverless Framework
        run: npm install -g serverless
          
      # Set the SERVERLESS_ACCESS_KEY for Serverless Framework
      - name: Set SERVERLESS_ACCESS_KEY
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV
      
      # Configure AWS credentials using the profile
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Publish the Lambda function
      - name: Publish Lambda project
        run: dotnet publish -c Release -r linux-x64 --self-contained false -o ./publish

      # Package the Lambda function (zip the published folder)
      - name: Package the Lambda function
        run: |
          cd ./publish
          zip -r ../lambda-package.zip .

      # Deploy Lambda with Serverless Framework
      - name: Deploy Lambda with Serverless
        run: |
          serverless deploy --stage prod  # You can specify different stages like prod or dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
